[29/12/2022 17:57:51 CET] ERROR rotkehlchen.api.rest Greenlet with id 4540114880: Greenlet for task 10 dies with exception: Found a <class 'rotkehlchen.fval.FVal'> object during Balance addition.
Exception Name: <class 'rotkehlchen.errors.misc.InputError'>
Exception Info: Found a <class 'rotkehlchen.fval.FVal'> object during Balance addition
Traceback:
   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/kelsos/development/rotki/rotki/rotkehlchen/api/rest.py", line 295, in _do_query_async
    result = command(**kwargs)
  File "/Users/kelsos/development/rotki/rotki/rotkehlchen/api/rest.py", line 665, in _query_blockchain_balances
    balances = self.rotkehlchen.chains_aggregator.query_balances(
  File "/Users/kelsos/development/rotki/rotki/rotkehlchen/utils/mixins/lockable.py", line 46, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/Users/kelsos/development/rotki/rotki/rotkehlchen/utils/mixins/cacheable.py", line 123, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/Users/kelsos/development/rotki/rotki/rotkehlchen/chain/aggregator.py", line 462, in query_balances
    getattr(self, query_method)(ignore_cache=ignore_cache)
  File "/Users/kelsos/development/rotki/rotki/rotkehlchen/utils/mixins/lockable.py", line 46, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/Users/kelsos/development/rotki/rotki/rotkehlchen/utils/mixins/cacheable.py", line 123, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/Users/kelsos/development/rotki/rotki/rotkehlchen/chain/aggregator.py", line 916, in query_eth_balances
    self._add_eth_protocol_balances(eth_balances=self.balances.eth)
  File "/Users/kelsos/development/rotki/rotki/rotkehlchen/chain/aggregator.py", line 1005, in _add_eth_protocol_balances
    eth_balances[address].assets[A_LQTY] += staked_info['staked'].amount
  File "/Users/kelsos/development/rotki/rotki/rotkehlchen/accounting/structures/balance.py", line 33, in __add__
    other = _evaluate_balance_input(other, 'addition')
  File "/Users/kelsos/development/rotki/rotki/rotkehlchen/accounting/structures/balance.py", line 78, in _evaluate_balance_input
    raise InputError(f'Found a {type(other)} object during Balance {operation}')