mcslender97@cloudshell:~ (yelp-data-eng)$ python json-to-pubsub.py
    --input 'gs://yelp-data-proj-bucket/yelp_academic_dataset_business.json' --topic projects/yelp--data-eng/topics/yelp-topic
INFO:root:Missing pipeline option (runner). Executing pipeline using the default runner: DirectRunner.
INFO:apache_beam.internal.gcp.auth:Setting socket default timeout to 60 seconds.
INFO:apache_beam.internal.gcp.auth:socket default timeout is 60.0 seconds.
Traceback (most recent call last):
  File "/home/mcslender97/json-to-pubsub.py", line 85, in <module>
    run()
  File "/home/mcslender97/json-to-pubsub.py", line 81, in run
    input_file | 'Write' >> pbs.WriteToPubSub(known_args.topic)
  File "/home/mcslender97/.local/lib/python3.9/site-packages/apache_beam/pipeline.py", line 597, in __exit__
    self.result = self.run()
  File "/home/mcslender97/.local/lib/python3.9/site-packages/apache_beam/pipeline.py", line 574, in run
    return self.runner.run_pipeline(self, self._options)
  File "/home/mcslender97/.local/lib/python3.9/site-packages/apache_beam/runners/direct/direct_runner.py", line 131, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/home/mcslender97/.local/lib/python3.9/site-packages/apache_beam/runners/direct/direct_runner.py", line 529, in run_pipeline
    pipeline.replace_all(_get_transform_overrides(options))
  File "/home/mcslender97/.local/lib/python3.9/site-packages/apache_beam/pipeline.py", line 514, in replace_all
    self._check_replacement(override)
  File "/home/mcslender97/.local/lib/python3.9/site-packages/apache_beam/pipeline.py", line 488, in _check_replacement
    self.visit(ReplacementValidator())
  File "/home/mcslender97/.local/lib/python3.9/site-packages/apache_beam/pipeline.py", line 623, in visit
    self._root_transform().visit(visitor, self, visited)
  File "/home/mcslender97/.local/lib/python3.9/site-packages/apache_beam/pipeline.py", line 1257, in visit
    part.visit(visitor, pipeline, visited)
  File "/home/mcslender97/.local/lib/python3.9/site-packages/apache_beam/pipeline.py", line 1257, in visit
    part.visit(visitor, pipeline, visited)
  File "/home/mcslender97/.local/lib/python3.9/site-packages/apache_beam/pipeline.py", line 1257, in visit
    part.visit(visitor, pipeline, visited)
  [Previous line repeated 4 more times]
  File "/home/mcslender97/.local/lib/python3.9/site-packages/apache_beam/pipeline.py", line 1260, in visit
    visitor.visit_transform(self)
  File "/home/mcslender97/.local/lib/python3.9/site-packages/apache_beam/pipeline.py", line 484, in visit_transform
    raise RuntimeError(
RuntimeError: Transform node AppliedPTransform(Read/Read/SDFBoundedSourceReader/ParDo(SDFBoundedSourceDoFn)/ProcessKeyedElements/GroupByKey/GroupByKey, _GroupByKeyOnly) was not replaced as expected.
-bash: --input: command not found
mcslender97@cloudshell:~ (yelp-data-eng)$