-bash-4.2$ combine -M AsymptoticLimits test_df_combine.txt --run blind
 <<< Combine >>> 
>>> random number generator seed is 123456
Will use a-priori expected background instead of a-posteriori one.
>>> method used is AsymptoticLimits
Error in <TFile::Init>: data/2017_shapes_df_input.csv not a ROOT file
Traceback (most recent call last):
  File "/afs/cern.ch/work/r/rymuelle/public/nanoAODzPrime/CMSSW_10_6_24/bin/slc7_amd64_gcc820/text2workspace.py", line 63, in <module>
    MB.doModel(justCheckPhysicsModel=options.justCheckPhysicsModel)
  File "/afs/cern.ch/work/r/rymuelle/public/nanoAODzPrime/CMSSW_10_6_24/python/HiggsAnalysis/CombinedLimit/ModelTools.py", line 110, in doModel
    if not justCheckPhysicsModel: self.doObservables()
  File "/afs/cern.ch/work/r/rymuelle/public/nanoAODzPrime/CMSSW_10_6_24/python/HiggsAnalysis/CombinedLimit/ShapeTools.py", line 61, in doObservables
    self.prepareAllShapes();
  File "/afs/cern.ch/work/r/rymuelle/public/nanoAODzPrime/CMSSW_10_6_24/python/HiggsAnalysis/CombinedLimit/ShapeTools.py", line 332, in prepareAllShapes
    shape = self.getShape(b,p); norm = 0;
  File "/afs/cern.ch/work/r/rymuelle/public/nanoAODzPrime/CMSSW_10_6_24/python/HiggsAnalysis/CombinedLimit/ShapeTools.py", line 503, in getShape
    if not file: raise RuntimeError, "Cannot open file %s (from pattern %s)" % (finalNames[0],names[0])
RuntimeError: Cannot open file data/2017_shapes_df_input.csv (from pattern data/2017_shapes_df_input.csv)
Error when running the combination:
	Failed to convert the input datacard from LandS to RooStats format. The lines above probably contain more information about the error.
