platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/lleri/cppbackend
plugins: xprocess-0.20.0, quickcheck-0.9.0
collected 8 items

cpp-backend-tests-practicum/tests/test_s02_server_logging.py FF......                                            [100%]

======================================================= FAILURES =======================================================
______________________________________________________ test_logs _______________________________________________________

server = <conftest.Server object at 0x7f251d94a530>

    def test_logs(server):
        log_json = server.get_log()
        assert log_json['message'] == 'Server has started...'
        assert log_json['data']['port'] == 8080
        assert log_json['data']['address'] == '0.0.0.0'
        request = 'images/cube.svg'
        res = server.get(f'/{request}')
        log_json = server.get_log()
        assert log_json['message'] == 'request received'
        assert log_json['data']['method'] == 'GET'
        assert log_json['data']['URI'] == '/images/cube.svg'
        log_json = server.get_log()
        assert log_json['message'] == 'response sent'
        assert log_json['data']['code'] == 200
>       assert log_json['data']['content_type'] == 'image/svg+xml'
E       KeyError: 'content_type'

cpp-backend-tests-practicum/tests/test_s02_server_logging.py:77: KeyError
------------------------------------------------ Captured stdout setup -------------------------------------------------
/home/lleri/cppbackend/.pytest_cache/d/.xprocess/server$ docker run --rm -p 8080:8080 my_http_server
process 'server' started pid=20165
{"timestamp":"2022-11-30T14:55:26.924711","data":{"port":8080,"address":"0.0.0.0"},"message":"Server has started..."}

server process startup detected
______________________________________________________ test_list _______________________________________________________

server = <conftest.Server object at 0x7f251d94a530>

    def test_list(server):
        request = 'api/v1/maps'
        res = server.get(f'/{request}')
        assert res.status_code == 200
        assert res.headers['content-type'] == 'application/json'
>       assert res.json() == ans_list
E       AssertionError: assert [{'id': 'map1...me': 'Map 2'}] == [{'id': 'map1...me': 'Map 1'}]
E         Left contains one more item: {'id': 'map2', 'name': 'Map 2'}
E         Use -v to get more diff

cpp-backend-tests-practicum/tests/test_s02_server_logging.py:85: AssertionError
-------------------------------- generated xml file: /home/lleri/cppbackend/results.xml --------------------------------
=============================================== short test summary info ================================================
FAILED cpp-backend-tests-practicum/tests/test_s02_server_logging.py::test_logs - KeyError: 'content_type'
FAILED cpp-backend-tests-practicum/tests/test_s02_server_logging.py::test_list - AssertionError: assert [{'id': 'map1...
============================================= 2 failed, 6 passed in 1.30s ==============================================